name: Pull Request

on:
  pull_request:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pull-request:
    name: Quality Checks
    if: ${{ github.head_ref != 'changeset-release/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: "**/package-lock.json"
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run Build
        run: npm run build

  chromatic:
    name: Run visual tests
    if: ${{ github.head_ref != 'changeset-release/master' }}
    uses: ./.github/workflows/chromatic.yml
    secrets: inherit
  