name: Pull Request

on:
  pull_request:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pull-request:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: "**/package-lock.json"
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run Build
        run: npm run build

      # - name: Deploy Chromatic
      #   uses: chromaui/action@latest
      #   with:
      #     projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      #     workingDir: ./packages/docs

  chromatic:
    name: Run visual tests
    uses: ./.github/workflows/chromatic.yml
    secrets: inherit