name: Release Pull Request

on:
  pull_request:
    types: [closed]
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-pr: 
    if: github.event.pull_request.merged == true && !startsWith(github.event.pull_request.head.ref, 'release/')
    name: Release Pull Request
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
        
      - name: Install dependencies
        run: npm install
      
      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
